HealthStats_player
FloatingText HealthStats_player.damageText
Referenced by Start.
bool HealthStats_player.disableDeaht
Referenced by DropStat.
float HealthStats_player.health
Referenced by AddStat, DropStat, Equipment.EquipmentAction, RegenerateHealth, ResetPlayer, Update.
float HealthStats_player.healthMax
Referenced by Equipment.EquipmentAction, ResetPlayer.
float HealthStats_player.healthRegeneration
Referenced by RegenerateHealth.
float HealthStats_player.expirience
Referenced by Update.
float HealthStats_player.energy
Referenced by AddStat, DropStat, RegenerateEnergy, ResetPlayer, Update.
float HealthStats_player.energyMax
Referenced by RegenerateEnergy, ResetPlayer.
float HealthStats_player.energyUseForDash
Referenced by DropStat.
float HealthStats_player.minimumEnergyForDash
Referenced by RegenerateEnergy.
float HealthStats_player.energyRegeneration
Referenced by RegenerateEnergy.
void HealthStats_player.Awake()
References HealthStatsAction.
void HealthStats_player.Start()
References damageText.
void HealthStats_player.Update()
References energy, expirience, health, RegenerateEnergy, RegenerateHealth.
void HealthStats_player.HealthStatsAction(String _typeOfAction, String _typeOfStat, float _value)
References AddStat, DropStat.
Referenced by Awake.
void HealthStats_player.RegenerateHealth()
References health, healthRegeneration.
Referenced by Update.
void HealthStats_player.RegenerateEnergy()
References InputManager.Dash, energy, energyMax, energyRegeneration, GameManager.inputManager, GameManager.instance, minimumEnergyForDash.
Referenced by Update.
void HealthStats_player.DropStat(String type, float value)
References InputManager.Dash, disableDeaht, energy, energyUseForDash, health, GameManager.inputManager, GameManager.instance.
Referenced by HealthStatsAction.
void HealthStats_player.AddStat(String _typeOfStat, float value)
References energy, health.
Referenced by HealthStatsAction.
void HealthStats_player.ResetPlayer()
References energy, energyMax, health, healthMax.