EnemyAI_Soul
AI_Type
float EnemyAI_Soul.lookRadius
Referenced by ActorActions, OnDrawGizmosSelected.
float EnemyAI_Soul.runRadius
Referenced by ActorMove.
float EnemyAI_Soul.attackRadius
Referenced by ActorAttack.
AI_Type EnemyAI_Soul.ai_Type
Referenced by ActorAttack, ActorMove.
float EnemyAI_Soul.damage
Referenced by ActorAttack.
float EnemyAI_Soul.attackDelay
Referenced by ActorAttack.
float EnemyAI_Soul.shootForce
Referenced by ActorAttack.
GameObject EnemyAI_Soul.projectile
Referenced by ActorAttack.
Transform EnemyAI_Soul.pfPojectile
Referenced by ActorAttack.
float EnemyAI_Soul.lastAttacked
Referenced by ActorAttack.
NavMeshAgent EnemyAI_Soul.navMeshAgent
Referenced by Start.
void EnemyAI_Soul.OnDrawGizmosSelected()
References lookRadius.
void EnemyAI_Soul.Awake()
References PlayerSpottedByEmeny.
void EnemyAI_Soul.Start()
References navMeshAgent.
void EnemyAI_Soul.Update()
References ActorActions.
void EnemyAI_Soul.PlayerSpottedByEmeny(Transform _nearbyEnemy)
Referenced by Awake.
void EnemyAI_Soul.ActorActions()
References ActorAttack, ActorMove, GameManager.instance, lookRadius, GameManager.playerManager.
Referenced by Update.
void EnemyAI_Soul.ActorMove(float distance)
References ai_Type, runRadius.
Referenced by ActorActions.
void EnemyAI_Soul.ActorAttack(float distance)
References ai_Type, attackDelay, attackRadius, damage, lastAttacked, pfPojectile, projectile, shootForce.
Referenced by ActorActions.