InputManager
float InputManager.moveX
Referenced by WASDMovement.
float InputManager.moveZ
Referenced by WASDMovement.
bool InputManager.inputWASD
Referenced by PlayerManager.MovementAnimations, WASDMovement.
bool InputManager.disableMovement
Referenced by DisableMovement, WASDMovement.
bool InputManager.disableDash
Referenced by Dash, DisableDash.
bool InputManager.disableMouse
Referenced by DisableMouse, LeftMouseButton, RightMouseButton.
bool InputManager.inventoryOpened
Referenced by OpenCloseInventory.
bool InputManager.disableInventory
Referenced by DisableInventory, OpenCloseInventory.
void InputManager.Awake()
References DisableDash, DisableInventory, DisableMouse, DisableMovement.
void InputManager.Update()
References Dash, OpenCloseInventory, WASDMovement.
void InputManager.DisableMovement(bool _value)
References disableMovement.
Referenced by Awake.
void InputManager.DisableDash(bool _value)
References disableDash.
Referenced by Awake.
void InputManager.DisableMouse()
References disableMouse.
Referenced by Awake, OpenCloseInventory.
void InputManager.OpenCloseInventory()
References disableInventory, DisableMouse, inventoryOpened.
Referenced by Update.
void InputManager.DisableInventory()
References disableInventory.
Referenced by Awake.
Vector3 InputManager.WASDMovement()
References disableMovement, inputWASD, moveX, moveZ.
Referenced by Update.
bool InputManager.Dash()
References disableDash.
Referenced by HealthStats_player.DropStat, PlayerManager.PlayerDash, HealthStats_player.RegenerateEnergy, Update.
bool InputManager.LeftMouseButton()
References disableMouse.
Referenced by PlayerManager.AttackAnimation.
bool InputManager.RightMouseButton()
References disableMouse.
Referenced by PlayerManager.DefenceAnimation.
bool InputManager.Interact()
Referenced by PlayerManager.OnTriggerStay.