PlayerManager
float PlayerManager.playerSpeed
Referenced by PlayerDash, Start.
float PlayerManager.dashSpeed
Referenced by PlayerDash.
CharacterController PlayerManager.charController
Referenced by Start.
GameObject PlayerManager.playerModel
Referenced by PlayerRotate.
BoxCollider PlayerManager.weaponCollider
Referenced by AnimationPlayer, UIGame.InventorySetActive, Start.
GameObject PlayerManager.rightHand
Referenced by Equipment.Clear, Equipment.EquipmentAction, Equipment.UpEqip.
Inventory PlayerManager.playerInventory
Referenced by UIInventory.UpdateInventory.
Equipment PlayerManager.playerEquipment
Referenced by AttackAnimation, DefenceAnimation, HealthStats_actor.OnTriggerEnter, UIInventory.UpdateEquipment.
bool PlayerManager.defenceState
Referenced by DefenceAnimation, Projectile.OnTriggerEnter.
float PlayerManager.speed
Referenced by PlayerDash, Start, Update.
Animator PlayerManager.playerAnim
Referenced by Start.
void PlayerManager.Awake()
References PlayerEqupmentAction, PlayerInventoryAction, ResetPlayer.
void PlayerManager.ResetPlayer()
Referenced by Awake.
void PlayerManager.Start()
References charController, playerAnim, playerSpeed, speed, weaponCollider.
void PlayerManager.OnTriggerStay(Collider other)
References GameManager.inputManager, GameManager.instance, InputManager.Interact.
void PlayerManager.Update()
References AnimationPlayer, PlayerDash, speed.
void PlayerManager.OnApplicationQuit()
void PlayerManager.AnimationPlayer()
References AttackAnimation, DefenceAnimation, MovementAnimations, weaponCollider.
Referenced by Update.
void PlayerManager.PlayerRotate()
References playerModel.
Referenced by MovementAnimations.
void PlayerManager.PlayerDash()
References InputManager.Dash, dashSpeed, GameManager.inputManager, GameManager.instance, playerSpeed, speed.
Referenced by Update.
void PlayerManager.MovementAnimations()
References GameManager.inputManager, InputManager.inputWASD, GameManager.instance, PlayerRotate.
Referenced by AnimationPlayer.
void PlayerManager.AttackAnimation()
References GameManager.inputManager, GameManager.instance, InputManager.LeftMouseButton, playerEquipment, Equipment.weaponSlot, ItemData.weaponType.
Referenced by AnimationPlayer.
void PlayerManager.DefenceAnimation()
References defenceState, GameManager.inputManager, GameManager.instance, playerEquipment, InputManager.RightMouseButton, Equipment.weaponSlot, ItemData.weaponType.
Referenced by AnimationPlayer.
void PlayerManager.PlayerInventoryAction(Inventory.InventoryActions _action, ItemData _item, int _count)
Referenced by Awake.
void PlayerManager.PlayerEqupmentAction(ItemData _item)
Referenced by Awake.