AudioManager
List<AudioClip> AudioManager.stepSounds
Referenced by PlayerStep.
List<AudioClip> AudioManager.enemySoulHit
Referenced by EnemyDamaged.
List<AudioClip> AudioManager.enemyRangeSoulShoot
Referenced by RangeSoulShoot.
List<AudioClip> AudioManager.doorOpens
Referenced by DoorOpens.
List<AudioClip> AudioManager.pickUp
Referenced by PickUp.
void AudioManager.Awake()
References DoorOpens, EnemyDamaged, PickUp, PlayerStep, RangeSoulShoot.
void AudioManager.PlayerStep()
References stepSounds.
Referenced by Awake.
void AudioManager.EnemyDamaged(AudioSource _source)
References enemySoulHit.
Referenced by Awake.
void AudioManager.RangeSoulShoot(AudioSource _source)
References enemyRangeSoulShoot.
Referenced by Awake.
void AudioManager.DoorOpens(AudioSource _source)
References doorOpens.
Referenced by Awake.
void AudioManager.PickUp(AudioSource _source)
References pickUp.
Referenced by Awake.